### ISSUE TITLE
Separate packages for each dialect

### ISSUE THREAD

**Issue by aacanakin** [slicebit/qb#121]
Currently, all dialect files resides in a single package. It is required to have separate packages for sqlite, postgres and mysql. Each package would require dialect and its tests.

Problems;
- In sub-packages, it is required to import qb package. While import cycles aren't allowed in go, we can't import sqlite package in root package.
- DialectRegistry wouldn't have any items since `init()` not called because we can't import driver on qb package

Solution;
- DialectRegistry won't be used in tests. Only dialect_test should have registry related tests
- It will be required to have blank imports to use the library for dialect registry to be filled.

This change would break the api.

**Comment by cdevienne** [comment]
For the import cycle problem, we can simply use a "qb_test" package name in the test files.

**Comment by cdevienne** [comment]
An important thing to do before that is to make sure all Clause structures have exported attributes.

**Comment by cdevienne** [comment]
Fixed by #137
