### ISSUE TITLE
Question: is qb go-routine safe ?

### ISSUE THREAD

**Issue by li3p** [slicebit/qb#77]
I have a plan to use qb in my project which used `gorm` before, but can `qb` of `qb.session` be shared by multiple go routines?

**Comment by li3p** [comment]
@aacanakin Thank you for your answer, it there a plan to implement a connection pool to make a session can be used in the go-routine safe manner ?

**Comment by aacanakin** [comment]
The session is going to be removed in 0.3 release. Currently, there exists a connection pool deep inside session. It can be reached using `db.Engine()`. The plan is to remove session completely because it isn't idiomatic.
